"""change sync identity columns from GENERATED ALWAYS to GENERATED BY DEFAULT

Revision ID: 070
Revises: 069
Create Date: 2026-05-27

"""
from alembic import op
import sqlalchemy as sa

revision = '070'
down_revision = '069'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Change identity columns from GENERATED ALWAYS to GENERATED BY DEFAULT
    # This allows explicit id values (e.g., from sync log retry after rollback)
    op.execute("ALTER TABLE sync_datasource ALTER COLUMN id SET GENERATED BY DEFAULT")
    op.execute("ALTER TABLE sync_table_mapping ALTER COLUMN id SET GENERATED BY DEFAULT")
    op.execute("ALTER TABLE sync_log ALTER COLUMN id SET GENERATED BY DEFAULT")


def downgrade() -> None:
    op.execute("ALTER TABLE sync_log ALTER COLUMN id SET GENERATED ALWAYS")
    op.execute("ALTER TABLE sync_table_mapping ALTER COLUMN id SET GENERATED ALWAYS")
    op.execute("ALTER TABLE sync_datasource ALTER COLUMN id SET GENERATED ALWAYS")
